import type { Metadata } from "next";
import "./globals.css";
import Sidebar from "./sidebar/page";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body className="bg-gray-100 text-gray-800">
      <div className="flex">
        <Sidebar />
        <main className="pl-10 pt-10 flex-1 bg-black text-white">
          {children}
        </main>
      </div>
    </body>
  </html>
  );
}
